#!/usr/bin/env bash

# Copyright 2016 Matt Oswalt. Use or modification of this
# source code is governed by the license provided here:
# https://github.com/Mierdin/todd/blob/master/LICENSE

echo '{"Hostname":["'$(hostname)'"]}'