#!/usr/bin/env bash

# Copyright 2016 Matt Oswalt. Use or modification of this
# source code is governed by the license provided here:
# https://github.com/toddproject/todd/blob/master/LICENSE

array_str='{"Addresses":["'

addresses=($(ip addr |  awk '/inet/{print $2}' | sed 's/\/.*//'))

for i in "${addresses[@]}"; do
    # process "$i"
    array_str=$array_str$i'","'
done

array_str=${array_str::-2}']}'

echo $array_str