---
docker_repo: 'deb https://apt.dockerproject.org/repo {{ ansible_distribution|lower }}-{{ ansible_distribution_release|lower }} main'
path: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/vagrant/go/bin:/usr/local/go/bin/:/home/vagrant/go/src/github.com/toddproject/todd/scripts
gopath: /home/vagrant/go
gosha256: '508028aac0654e993564b6e2014bf2d4a9751e3b286661b0b0040046cf18028e'
gotarball: 'go{{ gover }}.linux-amd64.tar.gz'
gourl: 'https://storage.googleapis.com/golang'
gover: '1.7.3'  #Change this variable to update to a new version of Go
todd_dir: '/home/vagrant/go/src/github.com/toddproject/todd'
todd_make_configureenv_check_file: '/home/vagrant/.make_configureenv_complete'
todd_compile_check_file: '/home/vagrant/.todd_compile_complete'
todd_path_exports:
  - file: '/home/vagrant/.profile'
    varname: 'GOPATH'
    varval: 'export GOPATH={{ gopath }}'
  - file: '/home/vagrant/.profile'
    varname: 'PATH'
    varval: 'export PATH={{ path }}'
  - file: '/home/vagrant/.bashrc'
    varname: 'GOPATH'
    varval: 'export GOPATH={{ gopath }}'
  - file: '/home/vagrant/.bashrc'
    varname: 'PATH'
    varval: 'export PATH={{ path }}'