#!/usr/bin/env python
import sys
sys.stdout.write('{"Interfaces":[{"Name":"lo0","HwAddr":"","IPv4Addrs":["127.0.0.1","127.94.0.3","127.94.0.1"],"IPv6Addrs":["::1","fe80::1"]},{"Name":"en0","HwAddr":"3c:15:c2:b9:11:58","IPv4Addrs":["10.12.0.174"],"IPv6Addrs":["fe80::3e15:c2ff:feb9:1158"]},{"Name":"awdl0","HwAddr":"02:ad:f1:51:cb:ba","IPv4Addrs":null,"IPv6Addrs":["fe80::ad:f1ff:fe51:cbba"]},{"Name":"vboxnet8","HwAddr":"0a:00:27:00:00:08","IPv4Addrs":["192.168.59.3"],"IPv6Addrs":null}]}')
